### ISSUE TITLE
Implement Automatic Profile Creation Using Device ID in OpenPanel Library

### ISSUE THREAD

**Issue by hitendigi** [Openpanel-dev/kotlin-sdk#3]
### Description:

Currently, in the OpenPanel library, a developer must explicitly call a function to create a user profile. Once a profile is created, all tracked events for that user are associated with their profile. However, many Android applications do not utilize user profiles, resulting in tracked events only being accessible through the events page. 

To address this, we propose using the device ID as a unique identifier for each event if an identity is not provided. This change would allow each event to be associated with a profile by default, making all features function effectively even in applications without a user system.

> **Reference**: Mixpanel uses a similar method by assigning a device ID when an identity isn’t specified, enabling seamless event tracking for applications without user systems.

### Requirements:

1. **Automatic Profile Creation**: Use the device ID as a unique identifier if an explicit identity is not provided. This will ensure that each event has a profile associated with it.
  
2. **Optional Profile Updating**: If a developer later chooses to implement user profiles, they can call the `identify()` function to update the profile data (e.g., first name, last name, and ID).
  
3. **Developer-Defined Unique ID**: If a developer has a custom unique ID, they should call `identify()` with their unique identifier, ensuring proper tracking of user events under that profile.

### Expected Outcome:

- **Enhanced Usability**: This solution makes the OpenPanel library more adaptable to Android apps without user profiles, allowing for event tracking through default profiles.
- **Flexibility**: Developers can later add profiles by calling `identify()` without an ID, mapping updated profile data to the existing tracked events.
  
### Tasks:

- Implement automatic profile creation based on device ID if no identity is specified.
- Update `identify()` to allow for seamless profile updates when user data is provided later.
  
### Notes:

This change will significantly improve OpenPanel's compatibility with Android apps that do not use user profiles, enhancing the library’s usability and versatility.

**Comment by lindesvard** [comment]
I do not want this to be default since its not GDPR compliant. The device identifier is an identifier and should be treated as such. 

If developers want to use it they can just call `identify` with the device identifier.

And the API is currently today creating profiles for each device but in a more anonymous way similar how other privacy focused analytics solution does it.

A user get a device_id which is hashed my a salt. `hash(project_id, ip, user-agent, salt)`, the salt is rotated once per day which will make it more privacy friendly.

So if you want to override this behaviour you can just call `identify` with a unique identifier (user_id, device identifier or what ever)

**Comment by hitendigi** [comment]
@lindesvard  So, are you saying that if no identifier is provided, the latest API still creates a profile for the user?

We're also using MixPanel, which has a similar identify function to override the default behavior. If no identifier is provided, it automatically creates a profile based on the device ID. Could you clarify if OpenPanel's behavior is aligned with this?

Additionally, if we collect the device ID through an Android app, we must disclose it in the Data Safety form for Play Store releases. This ensures transparency and confirms that we’re not collecting the ID without the user’s knowledge.

Could we explore an approach similar to MixPanel for OpenPanel? It would help align with industry standards while maintaining compliance. Let me know your thoughts!

**Comment by lindesvard** [comment]
> We're also using MixPanel, which has a similar identify function to override the default behavior. If no identifier is provided, it automatically creates a profile based on the device ID. Could you clarify if OpenPanel's behavior is aligned with this?

OpenPanel creates a "profile" for all users. But this profile will only work for 24 hours since the ID is calculated by `hash(project_id, ip, user-agent, salt)`. So if you visit an app 2 times it will look like 2 different users (this is for privacy reasons and thats how I want it). 

**But if you provide your own profile_id** it will override the default behaviour and you can visit the app 100 times and all sessions will be stored to that user. You can pick any identifier you want (deviceId, user id from db or what ever). 

> Additionally, if we collect the device ID through an Android app, we must disclose it in the Data Safety form for Play Store releases. This ensures transparency and confirms that we’re not collecting the ID without the user’s knowledge.

This is why I dont want to rely on device id. This is up to each developer to choose if they want to use the device id. Its just a matter of calling `identify()` after you have init OP.

Hope this clears things up a bit.

**Comment by hitendigi** [comment]
Okay then I will close this issue!
